---
- name: IntelliJ | Extract IntelliJ
  unarchive: src={{intellij_url}} dest={{base_dir}} creates={{intellij_home}} copy=no validate_certs=no
  tags: 
    - ide
    - intellij

- name: IntelliJ | Set softlink
  become: yes
  file: state=link force=yes
        src={{intellij_home}}
        dest={{base_dir}}/intellij
  tags:
    - ide
    - intellij
