---
- name: IntelliJ | Check IntelliJ Archive Exists
  stat: path={{intellij_download}}
  register: intellij_download_file
  tags: 
    - ide
    - intellij

- name: IntelliJ | Download IntelliJ
  get_url: url={{intellij_url}} dest={{intellij_download}} validate_certs=no
  when: not intellij_download_file.stat.exists
  tags: 
    - ide
    - intellij

- name: IntelliJ | Extract IntelliJ
  unarchive: src={{intellij_download}} dest={{base_dir}} creates={{intellij_home}} copy=no
  tags: 
    - ide
    - intellij

- name: IntelliJ | Set softlink
  become: yes
  file: state=link force=yes
        src={{intellij_home}}
        dest={{base_dir}}/intellij
  tags:
    - ide
    - intellij

- name: IntelliJ | Clean up
  file: path={{intellij_download}} state=absent
  tags: 
    - ide
    - intellij
