---
- name: Pycharm | Install Python Dev
  apt: pkg={{item}} state=present
  with_items:
    - python-dev
    - python-pip
  tags:
    - ide
    - pycharm

- name: Pycharm | Extract Pycharm
  unarchive: src={{pycharm_url}} dest={{base_dir}} creates={{pycharm_home}} copy=no validate_certs=no
  tags: 
    - ide
    - pycharm

- name: Pycharm | Set softlink
  become: yes
  file: state=link force=yes
        src={{pycharm_home}}
        dest={{base_dir}}/pycharm
  tags:
    - ide
    - pycharm
