---
repository: deb https://apt.dockerproject.org/repo ubuntu-xenial main
docker_compose_url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}