---
- name: Java | Check Java Archive Exists
  stat: path={{java_download}}
  register: java_download_file
  tags: java

- name: Java | Download Java
#  command: 'wget -q -o {{java_download}} --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" {{java_url}}'
  get_url: url={{java_url}} dest={{java_download}} validate_certs=no headers='Cookie:oraclelicense=accept-securebackup-cookie'
  when: not java_download_file.stat.exists
  tags: java

- name: Java | Extract Java
  unarchive: src={{java_download}} dest={{base_dir}} creates={{java_home}} copy=no
  tags: java

- name: Java | Set JAVA_HOME
  lineinfile: dest={{path_file}}
              state=present
              regexp='^export JAVA_HOME'
              line='export JAVA_HOME={{java_home}}'
              insertafter='EOF'
  tags: java

- name: Java | Set JRE_HOME
  lineinfile: dest={{path_file}}
              state=present
              regexp='^export JRE_HOME'
              line='export JRE_HOME={{java_jre_home}}'
              insertafter='EOF'
  tags: java

- name: Java | Set PATH
  lineinfile: dest={{path_file}}
              state=present
              regexp='export PATH=\$PATH:\$JAVA_HOME/bin:\$JRE_HOME/bin'
              line='export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
              insertafter='EOF'
  tags: java

- name: Java | Clean up
  file: path={{java_download}} state=absent
  tags: java
