---
- name: start docker
  become: yes
  service: name=docker state=started
  tags: docker

- name: restart docker
  become: yes
  service: name=docker state=restarted
  tags: docker

- name: reload docker
  become: yes
  service: name=docker state=reloaded
  tags: docker
