---
- name: MongoDB | Fetch GPG key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  tags: mongodb

- name: MongoDB | Add repository
  shell:
    echo "{{repository}}" | sudo tee /etc/apt/sources.list.d/{{mongodb_list}}
  tags: mongodb

- name: MongoDB | Install latest mongodb
  apt: pkg=mongodb-org update-cache=yes
  tags: mongodb

- name: MongoDB | Push default configuration template
  template:
    src=mongod.conf.j2
    dest={{mongodb_conf}}
    owner=root group=root mode=0644
  tags: mongodb

- name: MongoDB | Create systemd service file
  template:
    src=mongod.service.j2
    dest=/lib/systemd/system/mongod.service
    owner=root group=root mode=0644
  tags: mongodb
  notify:
  - restart mongodb

- name: MongoDB | Trigger mongodb restart
  meta: flush_handlers
  tags: mongodb

- name: MongoDB | Run mongo daemon
  service: name=mongod state=restarted
  tags: mongodb
