---
# GeoIP

- name: GeoIP.dat is present
  register: nginx_geoip_present
  stat:
    path: /usr/share/GeoIP/GeoIP.dat

- name: Make sure /usr/share/GeoIP is present
  file:
    path: '/usr/share/GeoIP'
    state: directory
    mode: '0755'

- name: Install unzip if missing
  apt:
    name: unzip
    state: present

- name: Download GeoIP.dat.gz
  get_url:
    url: '{{ geoip_download_url }}'
    dest: '/usr/share/GeoIP/GeoIP.dat.gz'
  register: new_archive
  when: nginx_geoip_present.stat.exists == false

- name: Unarchiv
  command: /bin/gunzip --force /usr/share/GeoIP/GeoIP.dat.gz > /usr/share/GeoIP/GeoIP.dat
  args:
    creates: /usr/share/GeoIP/GeoIP.dat
  ignore_errors: true
  when: nginx_geoip_present.stat.exists == false

- name: GeoIP.dat is present
  file:
    path: /usr/share/GeoIP/GeoIP.dat
    state: file
  when: nginx_geoip_present.stat.exists == false
