---
- hosts: all
  become: yes
  roles:
    - common
    - gui
    - ruby
    - nodejs
    - mongodb
    - yo
    - express
    - mysql
    - php
    - nginx
    - swift
    - java
    - maven
    - gradle
    - tomcat
    - ide
    - docker
    - sbt
