---
swift_version: "swift-3.0.1-RELEASE"
swift_platform: "ubuntu16.04"
swift_url: "https://swift.org/builds/swift-3.0.1-release/ubuntu1604/swift-3.0.1-RELEASE/{{swift_version}}-{{swift_platform}}.tar.gz"
swift_home: "{{base_dir}}/{{swift_version}}-{{swift_platform}}"
